### ISSUE TITLE
Enable the service worker

### ISSUE THREAD

**Issue by ebrehault** [collective/collective.experimental_angular_pwa#5]
Uncomment the service worker registration in index.html

**Comment by envy7** [comment]
The service worker was not commented from the start https://github.com/collective/collective.experimental_angular_pwa/blob/master/src/index.html
you can check here

**Comment by ebrehault** [comment]
what do you mean? as far as I can see, it **is** commented

**Comment by envy7** [comment]
oh that is redundant, I dont know how it came if you scroll down, you will see the same code block uncommented just before the ending body tag
